### ISSUE TITLE
Gamma distribution implementation differs from other

### ISSUE THREAD

**Issue by rohitjoshi** [boxtown/statrs#85]
`numpy.random_state` and `rand` crate gamma distribution function multiples end results with scale but statrs divides with scale. Any reason? 

rand::distribution::gamma: https://github.com/rust-lang-nursery/rand/blob/master/src/distributions/gamma.rs#L165

numpy rk_gamma: https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/distributions.c#L182

statrs gamma: https://github.com/boxtown/statrs/blob/master/src/distribution/gamma.rs#L414

**Comment by boxtown** [comment]
This is because `statrs` (which borrows its implementation from [Math.Net](https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Distributions/Gamma.cs#L401)) uses the `rate` parameter instead of `scale` which `numpy` uses. From [Wikipedia[(https://en.wikipedia.org/wiki/Gamma_distribution), `scale = 1/rate` so we divide instead of multiply.

**Comment by boxtown** [comment]
Closing this issue for now until we find a good reason to use `scale` over `rate`
